# Visit the Docker compose reference guide for more information
# https://docs.docker.com/compose/compose-file/

# develop app service
services:
  deno-jupyter:
    image: deno-jupyter:development
    container_name: deno-jupyter
    hostname: deno-devcontainer
    # build image from Dockerfile
    build: .
    volumes:
      # bind devcontainer files to container for reference
      - ../.devcontainer/:/home/deno/.devcontainer/
      # bind example deno notebook
      - ../example.deno.ipynb:/home/deno/example.deno.ipynb
      # bind workspace volume to clone deno projects
      - deno-jupyter:/home/deno
volumes:
  deno-jupyter:
    name: deno-workspace
    driver: local
