# Visit the Docker compose reference guide for more information
# https://docs.docker.com/compose/compose-file/

# develop app service
services:
  deno-devcontainer:
    image: deno-devcontainer:development
    container_name: deno-devcontainer
    hostname: deno-devcontainer
    # build image from Dockerfile
    build: .
    volumes:
      # bind devcontainer files to container for reference
      - ../.devcontainer/:/home/deno/.devcontainer/
      # bind vscode task files to container for reference
      - ../.vscode/:/home/deno/.vscode/
      # bind workspace volume to clone deno projects
      - deno-devcontainer:/home/deno
  postgres-db:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
    name: deno-pg-data
    driver: local
  deno-devcontainer:
    name: deno-pg-workspace
    driver: local
