# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/engine/reference/builder/

# Latest version of Deno on Debian
FROM denoland/deno:debian as devcontainer

# set working directory
WORKDIR /home/deno

CMD ["sleep", "infinity"]